main:
  - name: Posts
    url: /posts/
    weight: 2
  - name: Tags
    url: /tags/
    weight: 3
  - name: Categories
    url: /categories/
    weight: 4
  - name: Series
    url: /series/
    weight: 5
  - name: Projects
    url: /projects/
    weight: 6
  - name: About
    url: /authors/luizcarloscf
    weight: 7