main:
  - name: Posts
    url: /posts/
    weight: 2
  - name: Tags
    url: /tags/
    weight: 3
  - name: Categorias
    url: /categories/
    weight: 4
  - name: SÃ©ries
    url: /series/
    weight: 5
  - name: Projetos
    url: /projects/
    weight: 6
  - name: Sobre
    url: /authors/luizcarloscf
    weight: 7